"""Initial schema

Revision ID: 600eddf26ab2
Revises: 
Create Date: 2026-03-24 15:12:45.327527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '600eddf26ab2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('businesses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('schedule', sa.String(), nullable=True),
    sa.Column('location_url', sa.String(), nullable=True),
    sa.Column('plan_type', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_businesses_id'), 'businesses', ['id'], unique=False)
    op.create_index(op.f('ix_businesses_slug'), 'businesses', ['slug'], unique=True)
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('origin', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contacts_business_id'), 'contacts', ['business_id'], unique=False)
    op.create_index(op.f('ix_contacts_id'), 'contacts', ['id'], unique=False)
    op.create_table('game_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('rule', sa.String(), nullable=True),
    sa.Column('daily_limit', sa.String(), nullable=True),
    sa.Column('time_window', sa.String(), nullable=True),
    sa.Column('winner_message', sa.String(), nullable=True),
    sa.Column('loser_message', sa.String(), nullable=True),
    sa.Column('play_rule', sa.String(), nullable=True),
    sa.Column('stock', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_configs_business_id'), 'game_configs', ['business_id'], unique=False)
    op.create_index(op.f('ix_game_configs_id'), 'game_configs', ['id'], unique=False)
    op.create_table('game_spins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('won', sa.Boolean(), nullable=True),
    sa.Column('prize_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_spins_business_id'), 'game_spins', ['business_id'], unique=False)
    op.create_index(op.f('ix_game_spins_id'), 'game_spins', ['id'], unique=False)
    op.create_table('module_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('offers', sa.Boolean(), nullable=True),
    sa.Column('raffle', sa.Boolean(), nullable=True),
    sa.Column('chat', sa.Boolean(), nullable=True),
    sa.Column('game', sa.Boolean(), nullable=True),
    sa.Column('qr', sa.Boolean(), nullable=True),
    sa.Column('terms', sa.Boolean(), nullable=True),
    sa.Column('schedule', sa.Boolean(), nullable=True),
    sa.Column('location', sa.Boolean(), nullable=True),
    sa.Column('whatsapp', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_module_configs_business_id'), 'module_configs', ['business_id'], unique=False)
    op.create_index(op.f('ix_module_configs_id'), 'module_configs', ['id'], unique=False)
    op.create_table('offers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('price', sa.String(), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_offers_business_id'), 'offers', ['business_id'], unique=False)
    op.create_index(op.f('ix_offers_id'), 'offers', ['id'], unique=False)
    op.create_table('raffle_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raffle_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raffle_entries_id'), 'raffle_entries', ['id'], unique=False)
    op.create_index(op.f('ix_raffle_entries_raffle_id'), 'raffle_entries', ['raffle_id'], unique=False)
    op.create_table('raffles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('prize', sa.String(), nullable=False),
    sa.Column('draw_date', sa.String(), nullable=True),
    sa.Column('time_window', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raffles_business_id'), 'raffles', ['business_id'], unique=False)
    op.create_index(op.f('ix_raffles_id'), 'raffles', ['id'], unique=False)
    op.create_table('terms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_terms_business_id'), 'terms', ['business_id'], unique=False)
    op.create_index(op.f('ix_terms_id'), 'terms', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'BUSINESS', name='roleenum'), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_terms_id'), table_name='terms')
    op.drop_index(op.f('ix_terms_business_id'), table_name='terms')
    op.drop_table('terms')
    op.drop_index(op.f('ix_raffles_id'), table_name='raffles')
    op.drop_index(op.f('ix_raffles_business_id'), table_name='raffles')
    op.drop_table('raffles')
    op.drop_index(op.f('ix_raffle_entries_raffle_id'), table_name='raffle_entries')
    op.drop_index(op.f('ix_raffle_entries_id'), table_name='raffle_entries')
    op.drop_table('raffle_entries')
    op.drop_index(op.f('ix_offers_id'), table_name='offers')
    op.drop_index(op.f('ix_offers_business_id'), table_name='offers')
    op.drop_table('offers')
    op.drop_index(op.f('ix_module_configs_id'), table_name='module_configs')
    op.drop_index(op.f('ix_module_configs_business_id'), table_name='module_configs')
    op.drop_table('module_configs')
    op.drop_index(op.f('ix_game_spins_id'), table_name='game_spins')
    op.drop_index(op.f('ix_game_spins_business_id'), table_name='game_spins')
    op.drop_table('game_spins')
    op.drop_index(op.f('ix_game_configs_id'), table_name='game_configs')
    op.drop_index(op.f('ix_game_configs_business_id'), table_name='game_configs')
    op.drop_table('game_configs')
    op.drop_index(op.f('ix_contacts_id'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_business_id'), table_name='contacts')
    op.drop_table('contacts')
    op.drop_index(op.f('ix_businesses_slug'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_id'), table_name='businesses')
    op.drop_table('businesses')
    # ### end Alembic commands ###
